name: Backend Pipeline

on:
  push:
    branches:
      - main
    paths:
      - "backend/**"
  pull_request:
    branches:
      - main
    paths:
      - "backend/**"
  workflow_dispatch:

jobs:
  build_and_deploy_backend_main:
    if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
    name: Build and Deploy Lambda (Main Branch)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Build Express.js project
        run: cd backend && npm install && npm run build:lambda && cd dist && zip -r backend.zip . && mv backend.zip ../../

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy to AWS Lambda
        id: deploy
        run: aws lambda update-function-code --function-name cop4331-express-lambda --zip-file fileb://backend.zip --publish

  build_and_deploy_backend_pull_request:
    if: ${{ github.event_name == 'pull_request' }}
    name: Build and Deploy Lambda (Pull Request)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Build Express.js project
        run: cd backend && npm install && npm run build:lambda && cd dist && zip -r backend.zip . && mv backend.zip ../../

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy to AWS Lambda
        id: deploy
        run: aws lambda update-function-code --function-name cop4331-express-lambda-dev --zip-file fileb://backend.zip --publish
